import React, { useEffect, useState } from 'react';
import { MapContainer, TileLayer, GeoJSON, Marker, Popup, useMap, useMapEvents, LayersControl } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';

const { BaseLayer } = LayersControl;

// Custom Church Icon using the official processed SDA logo (Scaled down for clarity)
const churchIcon = L.icon({
  iconUrl: '/sda_logo.svg',
  iconSize: [28, 28],
  iconAnchor: [14, 14],
  popupAnchor: [0, -14]
});

function MapEvents({ onZoomEnd }) {
  useMapEvents({
    zoomend: (e) => {
      onZoomEnd(e.target.getZoom());
    }
  });
  return null;
}

function MapViewSetter({ bounds }) {
  const map = useMap();
  useEffect(() => {
    if (bounds) {
      map.fitBounds(bounds, { padding: [50, 50], animate: true });
    }
  }, [bounds, map]);
  return null;
}

function InitialFocus({ onFocus, geojsonData }) {
  const map = useMap();
  const [init, setInit] = useState(false);

  useEffect(() => {
    if (geojsonData?.features?.length > 0 && !init) {
      const bounds = L.geoJSON(geojsonData).getBounds();
      if (bounds.isValid()) {
        onFocus(bounds);
        setInit(true);
      }
    }
  }, [geojsonData, init, onFocus]);

  return null;
}

const DistrictMap = ({ districts, churches = [], selectedDistrict, showBoundaries, onSelect }) => {
  const [mapBounds, setMapBounds] = useState(null);
  const [zimBoundary, setZimBoundary] = useState(null);
  const [currentZoom, setCurrentZoom] = useState(7);
  const [territories, setTerritories] = useState(null);
  const CHURCH_VISIBILITY_THRESHOLD = 8; // Show churches earlier when zooming in (District level)
  const TERRITORY_VISIBILITY_THRESHOLD = 9; // Show territories slightly later for clarity

  // Fetch National boundary
  useEffect(() => {
      fetch('https://raw.githubusercontent.com/glynnbird/countriesgeojson/master/zimbabwe.geojson')
        .then(res => res.json())
        .then(data => setZimBoundary(data))
        .catch(err => console.error('Failed to load Zim boundary:', err));
  }, []);

  // Fetch Church Territories (Generated by GIS script)
  useEffect(() => {
    const fetchTerritories = async () => {
      try {
        const configRes = await fetch(`/gis_config.json?v=${Date.now()}`);
        if (!configRes.ok) return;
        const config = await configRes.json();
        
        const geoRes = await fetch(`${config.latestFile}?v=${config.version}`);
        if (geoRes.ok) {
           const data = await geoRes.json();
           setTerritories(data);
        }
      } catch (err) {
        console.warn('GIS data registry not ready yet...');
      }
    };
    
    fetchTerritories();
    const interval = setInterval(fetchTerritories, 30000); // Check for new versions every 30s
    return () => clearInterval(interval);
  }, []);

  const districtStyle = (feature) => {
    const isSelected = selectedDistrict?.id === feature.properties?.id;
    return {
      fillColor: isSelected ? '#2E7D32' : '#8DA38D',
      weight: isSelected ? 4 : 3,
      opacity: 1,
      color: isSelected ? '#F9A825' : '#2563eb', // Mission Blue
      fillOpacity: isSelected ? 0.3 : 0.1,
    };
  };

  const zimStyle = {
      fillColor: 'transparent',
      weight: 2,
      color: '#2E7D32',
      opacity: 0.1,
      dashArray: '5, 10',
      interactive: false
  };

  const territoryStyle = (feature) => {
    // Generate a semi-random color based on church_id/name for distinct territories
    const colors = ['#2E7D32', '#388E3C', '#43A047', '#4CAF50', '#66BB6A', '#81C784', '#A5D6A7'];
    const id = feature.properties.church_id || feature.properties.name || '';
    const hash = id.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
    const color = colors[hash % colors.length];

    return {
      fillColor: color,
      weight: 1.5,
      opacity: 0.8,
      color: '#D32F2F', // Professional red boundary between territories
      fillOpacity: 0.3,
    };
  };

  const onEachFeature = (feature, layer) => {
    layer.on({
      mouseover: (e) => {
        const l = e.target;
        l.setStyle({ fillOpacity: 0.5, color: '#60a5fa' });
      },
      mouseout: (e) => {
        const l = e.target;
        l.setStyle({ 
          fillOpacity: selectedDistrict?.id === feature.properties.id ? 0.3 : 0.1, 
          color: selectedDistrict?.id === feature.properties.id ? '#F9A825' : '#2563eb' 
        });
      },
      click: (e) => {
        const d = districts.find(dist => dist.id === feature.properties.id);
        if (d) onSelect(d);
        setMapBounds(e.target.getBounds());
      }
    });
  };

  const geojsonData = {
    type: 'FeatureCollection',
    features: districts.map(d => ({
      type: 'Feature',
      id: d.id,
      properties: { ...d },
      geometry: typeof d.geom === 'string' ? JSON.parse(d.geom) : d.geom
    }))
  };

  return (
    <MapContainer 
      center={[-19.0154, 29.1549]} 
      zoom={7} 
      style={{ height: '100%', width: '100%' }}
      className="z-0 grayscale-[0.2] contrast-[1.1]"
    >
      <LayersControl position="topright">
        <BaseLayer checked name="Institutional Light">
          <TileLayer
            attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png"
          />
        </BaseLayer>
        <BaseLayer name="Google Hybrid">
          <TileLayer
            attribution='&copy; Google'
            url="https://{s}.google.com/vt/lyrs=s,h&x={x}&y={y}&z={z}"
            subdomains={['mt0', 'mt1', 'mt2', 'mt3']}
          />
        </BaseLayer>
      </LayersControl>
      
      <MapEvents onZoomEnd={setCurrentZoom} />
      
      {/* Permanent National Border */}
      {zimBoundary && (
          <GeoJSON data={zimBoundary} style={zimStyle} />
      )}

      {/* Church Territories - FEATURE REVEAL */}
      {currentZoom >= TERRITORY_VISIBILITY_THRESHOLD && territories && (
        <GeoJSON 
          key={`territories-${territories.features.length}`}
          data={territories}
          style={territoryStyle}
          onEachFeature={(feature, layer) => {
            layer.bindPopup(`
              <div class="p-1 font-sans">
                <p class="text-[9px] uppercase font-bold text-slate-400 mb-0">Demarcated Territory</p>
                <h4 class="text-xs font-black text-[#2E7D32] uppercase">${feature.properties.church_name || feature.properties.name}</h4>
                <p class="text-[10px] text-slate-600 italic">Sector: ${feature.properties.district}</p>
              </div>
            `);
          }}
        />
      )}

      {/* District Polygons */}
      {showBoundaries && districts.length > 0 && (
        <GeoJSON 
          key={`districts-${districts.length}-${showBoundaries}-${districts.map(d => d.id).join(',')}`}
          data={geojsonData} 
          style={districtStyle}
          onEachFeature={onEachFeature}
        />
      )}

      {/* Church Markers - SCALE BASED VISIBILITY */}
      {currentZoom >= CHURCH_VISIBILITY_THRESHOLD && churches.map((church) => {
          const geom = typeof church.geom === 'string' ? JSON.parse(church.geom) : church.geom;
          if (!geom || !geom.coordinates) return null;
          
          return (
            <Marker 
              key={church.id}
              position={[geom.coordinates[1], geom.coordinates[0]]}
              icon={churchIcon}
            >
               <Popup className="premium-popup">
                <div className="p-3 min-w-[220px] bg-[#F8FAF8] text-[#1A2E1A] rounded-none shadow-xl border border-[#D0E8D0]">
                  <div className="flex items-center gap-3 mb-3 pb-2 border-b border-[#E8F0E8]">
                     <div className="w-8 h-8 flex items-center justify-center shrink-0">
                        <img src="/sda_logo.svg" alt="SDA Symbol" className="w-full h-full object-contain" />
                     </div>
                     <h3 className="text-sm font-black tracking-tight text-[#1A2E1A] leading-tight uppercase">{church.name}</h3>
                  </div>
                  
                  <div className="space-y-3">
                    <div>
                        <p className="text-[9px] text-slate-400 uppercase font-black tracking-[0.15em] mb-0.5">Classification</p>
                        <p className="text-xs text-slate-600 font-semibold">{church.category}</p>
                    </div>
                    
                    <div>
                        <p className="text-[9px] text-[#1A2E1A]/40 uppercase font-black tracking-[0.15em] mb-0.5">Assigned Shepherd</p>
                        <div className="flex items-center gap-2">
                            <div className="w-1.5 h-1.5 bg-[#2E7D32] rounded-full"></div>
                            <p className="text-xs text-[#2E7D32] font-black uppercase tracking-tighter">{church.pastor_name}</p>
                        </div>
                    </div>
                  </div>
                </div>
              </Popup>
            </Marker>
          );
      })}

      {/* Persistent Mission Region Focus Hook */}
      <MapViewSetter bounds={mapBounds} />
      
      {/* Automate Initial Perspective Focus */}
      <InitialFocus onFocus={setMapBounds} geojsonData={geojsonData} />
    </MapContainer>
  );
};

export default DistrictMap;
